In [ ]:
#import libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
#upload and display file
df = pd.read_csv('/content/spam_ham_dataset.csv')
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [ ]:
#Column names
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [ ]:
df.shape

(5171, 4)

In [ ]:
#check for duplicates
df.drop_duplicates(inplace = True)
df.shape

#no dupliatesm

(5171, 4)

In [ ]:
df.isnull().sum()
#no null values

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [ ]:
#downloading stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def process_text(text):
  #remove punctuations
  #remove stopwords
  #return a list of clean words
#1
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)
#2
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
#3
  return clean_words

In [ ]:
#tokenization
df['text'].head().apply(process_text)

0    [Subject, enron, methanol, meter, 988291, foll...
1    [Subject, hpl, nom, january, 9, 2001, see, att...
2    [Subject, neon, retreat, ho, ho, ho, around, w...
3    [Subject, photoshop, windows, office, cheap, m...
4    [Subject, indian, springs, deal, book, teco, p...
Name: text, dtype: object

In [ ]:
#convert collection of words into matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
messages_bow=CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [ ]:
#split into train and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(messages_bow,df['label_num'],test_size=0.20,random_state = 0)

In [ ]:
#getting the shape of messages_bow(bag of words) that holds different words as tokens
messages_bow.shape

(5171, 50381)

In [ ]:
#create and train Naive Bayes classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train,y_train)

In [ ]:
#print the predictions
print(classifier.predict(x_train))

#print actual values
print(y_train.values)

[0 0 0 ... 1 0 0]
[0 0 0 ... 1 0 0]


In [ ]:
from nltk.metrics import confusionmatrix
#evaluate the model
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred = classifier.predict(x_train)
print(classification_report(y_train,pred))
print('\n Confusion Matrix : \n',confusion_matrix(y_train,pred))
print('\n Accuracy : \n',accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2940
           1       0.98      0.97      0.98      1196

    accuracy                           0.99      4136
   macro avg       0.99      0.98      0.98      4136
weighted avg       0.99      0.99      0.99      4136


 Confusion Matrix : 
 [[2918   22]
 [  30 1166]]

 Accuracy : 
 0.9874274661508704


In [ ]:
#working on test dataset
#print the predictions
print(classifier.predict(x_test))

#print actual values
print(y_test.values)

[0 0 0 ... 0 1 0]
[0 0 0 ... 0 1 0]


In [ ]:
#to evaluate testing model
pred = classifier.predict(x_test)
print(classification_report(y_test,pred))
print('\n Confusion Matrix : \n',confusion_matrix(y_test,pred))
print('\n Accuracy : \n',accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       732
           1       0.95      0.96      0.96       303

    accuracy                           0.97      1035
   macro avg       0.97      0.97      0.97      1035
weighted avg       0.97      0.97      0.97      1035


 Confusion Matrix : 
 [[718  14]
 [ 13 290]]

 Accuracy : 
 0.9739130434782609
